version: "3.9"

services:
  godockerui:
    image: golang:1.24
    working_dir: /app
    command: sh -c "go mod tidy && go run ./cmd/server"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
